// <auto-generated />
using System;
using Devify.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Devify.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231024021504_24102023")]
    partial class _24102023
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Devify.Entity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ff045d07-be86-4a4e-bfa4-0264ec832c12",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b794aa62-49da-4045-9c43-2b048da2ba24",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "SUPERADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEMc7mKj2GuhMdUUrGahZkca/SbuaYIUjA75qvOcnOeYc49kx9j/Ovba9Ojgx6XVj+Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6335ba2b-51f6-4a34-9e34-c65f1df71f4a",
                            TwoFactorEnabled = false,
                            UserName = "SuperAdmin"
                        },
                        new
                        {
                            Id = "e0ed2b3d-2c72-4a84-bd60-1ff9a78ee084",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a9f1372e-2e31-4d82-9c5f-2457e9879513",
                            Email = "manager@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MANAGER@GMAIL.COM",
                            NormalizedUserName = "SUPERMANAGER",
                            PasswordHash = "AQAAAAIAAYagAAAAEEeSzQ+1uZ3TsGEfBBjmxO5cYOuR2YHgigoEfeQYwVrC3k8Xq3Xe7lFMBaLLtVOzhQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d51f7846-eab0-4ef5-a101-40821c80404f",
                            TwoFactorEnabled = false,
                            UserName = "SuperManager"
                        },
                        new
                        {
                            Id = "8b4a17e1-4a1a-44e3-9a95-c2b59b7a7a4c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "39d10025-b9e5-4fef-98fa-273adea56f79",
                            Email = "duocdev26@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DUOCDEV26@GMAIL.COM",
                            NormalizedUserName = "DUOCDEV",
                            PasswordHash = "AQAAAAIAAYagAAAAEAZrtRJneOKVmZJ+/d3+gLHEVnrh/EtCTEIfQiHG2k87gqlAv0LtEg/cxFUKYtjFlw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "96f7c687-6fb6-47eb-a8e4-8c06affac188",
                            TwoFactorEnabled = false,
                            UserName = "DuocDev"
                        },
                        new
                        {
                            Id = "d9e03227-9b87-40b5-9c7b-3a8578b6c04c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "215fd385-7faa-4304-a5c8-23cc828e350b",
                            Email = "codedao6@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CODEDAO@GMAIL.COM",
                            NormalizedUserName = "TOIDICODEDAO",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ7fipmCwB65TKdhaWNdW4LHRkumqreDw+jTtWq3gN2i9NHoLmgKM8T3rdlkUjXLog==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ab06a85e-2217-4e89-8699-dc3bcee7b152",
                            TwoFactorEnabled = false,
                            UserName = "ToiDiCodeDao"
                        },
                        new
                        {
                            Id = "51274390-9171-49dd-a3e7-6e23fbf327fb",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b0669c87-74de-4a99-8ddc-a2456aa59ac1",
                            Email = "hoidanit@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "HOIDANIT@GMAIL.COM",
                            NormalizedUserName = "HOIDANIT",
                            PasswordHash = "AQAAAAIAAYagAAAAEMxTpx5CZdNhZZR0xrJ1aPgRkL9IzsHOXeBI75tyQHhwwozyPtzG7JNasodUJcqzxg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "10a57b28-7d55-4449-bbcc-5bd49d8eabdb",
                            TwoFactorEnabled = false,
                            UserName = "HoiDanIT"
                        },
                        new
                        {
                            Id = "9b2eb0a3-7d3c-4671-8d16-30c69d20a7c9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3a0bf3fa-7172-4722-a2ea-15730a63d0d5",
                            Email = "tedulms@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "TEDULMS@GMAIL.COM",
                            NormalizedUserName = "TEDULMS",
                            PasswordHash = "AQAAAAIAAYagAAAAEGlwhaw9oe3Q6XLvz11cyt+UjaE+YRzzmdmEQO+0k8vLv3PCPeZQTK/cj6g/nD0HGA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c91dc6ac-eda4-4ae9-876a-b62ceead4857",
                            TwoFactorEnabled = false,
                            UserName = "TeduLMS"
                        },
                        new
                        {
                            Id = "3f9f0d9e-67af-4a8d-9aa6-5f2270fc9fbb",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0e830c6c-0287-412f-b58c-001a0a62f42c",
                            Email = "customer@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER@GMAIL.COM",
                            NormalizedUserName = "CUSTOMER",
                            PasswordHash = "AQAAAAIAAYagAAAAEJjwax+aZHF+o9q3DugayodzRleweiqYKmAlqh2dfksuyZd0H+p/m9InnQKVXHvVfw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f4dd9a13-76eb-4634-adc8-652c74f08ea9",
                            TwoFactorEnabled = false,
                            UserName = "Customer"
                        },
                        new
                        {
                            Id = "6e6e4976-631d-46fb-91ea-11e70fb7087a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "05eae9d6-3e89-49e7-bc52-161827666f97",
                            Email = "clone@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CLONE@GMAIL.COM",
                            NormalizedUserName = "CLONE",
                            PasswordHash = "AQAAAAIAAYagAAAAEMpBuhxXPM8EnrSg07XeD782/RLtTm7l0Gje3sGSxtZHUkJQQT1qy5Zo0E6bmIVZzA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "56295ac2-636d-4b6d-b406-863e2549ccf5",
                            TwoFactorEnabled = false,
                            UserName = "Clone"
                        },
                        new
                        {
                            Id = "2b2e0d9b-74dd-4928-8c24-1a3156d9fc41",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d2ff0855-2988-45d8-885a-cb2dc9b8b5d0",
                            Email = "guest@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "GUEST@GMAIL.COM",
                            NormalizedUserName = "GUEST",
                            PasswordHash = "AQAAAAIAAYagAAAAENZv56h33AVhndOvH95SISTt8FpO13IYkzKGp/toka4B+x2Spj+bHMPXlE42aA+w8Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4dae6c66-c105-46a3-967e-bdf1dc34a8dc",
                            TwoFactorEnabled = false,
                            UserName = "Guest"
                        });
                });

            modelBuilder.Entity("Devify.Entity.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Devify.Entity.Chapter", b =>
                {
                    b.Property<Guid>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("Step")
                        .HasColumnType("int");

                    b.HasKey("ChapterId");

                    b.HasIndex("CourseId");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("Devify.Entity.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Devify.Entity.Course", b =>
                {
                    b.Property<Guid>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseLevelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<long>("Purchased")
                        .HasColumnType("bigint");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CourseLevelId");

                    b.HasIndex("CreatorId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Devify.Entity.CourseLevel", b =>
                {
                    b.Property<string>("CourseLevelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LevelDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("CourseLevelId");

                    b.ToTable("CourseLevels");
                });

            modelBuilder.Entity("Devify.Entity.Course_Language", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CourseId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("Course_Languages");
                });

            modelBuilder.Entity("Devify.Entity.Creator", b =>
                {
                    b.Property<string>("CreatorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AboutMe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CreatorId");

                    b.ToTable("Creators");
                });

            modelBuilder.Entity("Devify.Entity.DetailOrder", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CoursePrice")
                        .HasColumnType("float");

                    b.HasKey("OrderId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("DetailOrders");
                });

            modelBuilder.Entity("Devify.Entity.Language", b =>
                {
                    b.Property<string>("LanguageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageId");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Devify.Entity.Lesson", b =>
                {
                    b.Property<Guid>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChapterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("Step")
                        .HasColumnType("int");

                    b.Property<string>("Video")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LessonId");

                    b.HasIndex("ChapterId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("Devify.Entity.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Devify.Entity.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<string>("UserBuyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrderId");

                    b.HasIndex("UserBuyId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Devify.Entity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Expired")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Devify.Entity.Slider", b =>
                {
                    b.Property<int>("SliderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SliderId"));

                    b.Property<string>("Button")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SliderId");

                    b.ToTable("Sliders");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2ca8fa08-4a80-4714-a5fb-17b7316fddc4",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "c6de4ab5-2df7-4a6c-9bbd-2e1b68f8ebdd",
                            Name = "Creator",
                            NormalizedName = "CREATOR"
                        },
                        new
                        {
                            Id = "f28ad7f6-6c3d-4f0f-b9a4-60bca4b57bb3",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "ff045d07-be86-4a4e-bfa4-0264ec832c12",
                            RoleId = "2ca8fa08-4a80-4714-a5fb-17b7316fddc4"
                        },
                        new
                        {
                            UserId = "e0ed2b3d-2c72-4a84-bd60-1ff9a78ee084",
                            RoleId = "2ca8fa08-4a80-4714-a5fb-17b7316fddc4"
                        },
                        new
                        {
                            UserId = "8b4a17e1-4a1a-44e3-9a95-c2b59b7a7a4c",
                            RoleId = "c6de4ab5-2df7-4a6c-9bbd-2e1b68f8ebdd"
                        },
                        new
                        {
                            UserId = "d9e03227-9b87-40b5-9c7b-3a8578b6c04c",
                            RoleId = "c6de4ab5-2df7-4a6c-9bbd-2e1b68f8ebdd"
                        },
                        new
                        {
                            UserId = "51274390-9171-49dd-a3e7-6e23fbf327fb",
                            RoleId = "c6de4ab5-2df7-4a6c-9bbd-2e1b68f8ebdd"
                        },
                        new
                        {
                            UserId = "9b2eb0a3-7d3c-4671-8d16-30c69d20a7c9",
                            RoleId = "c6de4ab5-2df7-4a6c-9bbd-2e1b68f8ebdd"
                        },
                        new
                        {
                            UserId = "3f9f0d9e-67af-4a8d-9aa6-5f2270fc9fbb",
                            RoleId = "f28ad7f6-6c3d-4f0f-b9a4-60bca4b57bb3"
                        },
                        new
                        {
                            UserId = "6e6e4976-631d-46fb-91ea-11e70fb7087a",
                            RoleId = "f28ad7f6-6c3d-4f0f-b9a4-60bca4b57bb3"
                        },
                        new
                        {
                            UserId = "2b2e0d9b-74dd-4928-8c24-1a3156d9fc41",
                            RoleId = "f28ad7f6-6c3d-4f0f-b9a4-60bca4b57bb3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Devify.Entity.Chapter", b =>
                {
                    b.HasOne("Devify.Entity.Course", "Course")
                        .WithMany("Chapters")
                        .HasForeignKey("CourseId");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Devify.Entity.Comment", b =>
                {
                    b.HasOne("Devify.Entity.Lesson", "Lesson")
                        .WithMany("Comments")
                        .HasForeignKey("LessonId");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Devify.Entity.Course", b =>
                {
                    b.HasOne("Devify.Entity.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Devify.Entity.CourseLevel", "CourseLevel")
                        .WithMany("Courses")
                        .HasForeignKey("CourseLevelId");

                    b.HasOne("Devify.Entity.Creator", "Creator")
                        .WithMany("Courses")
                        .HasForeignKey("CreatorId");

                    b.Navigation("Category");

                    b.Navigation("CourseLevel");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Devify.Entity.Course_Language", b =>
                {
                    b.HasOne("Devify.Entity.Course", "Course")
                        .WithMany("CourseLanguages")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Devify.Entity.Language", "Language")
                        .WithMany("CourseLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Devify.Entity.Creator", b =>
                {
                    b.HasOne("Devify.Entity.ApplicationUser", "User")
                        .WithOne("Creator")
                        .HasForeignKey("Devify.Entity.Creator", "CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Devify.Entity.DetailOrder", b =>
                {
                    b.HasOne("Devify.Entity.Course", "Course")
                        .WithMany("DetailOrders")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Devify.Entity.Order", "Order")
                        .WithMany("DetailOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Devify.Entity.Lesson", b =>
                {
                    b.HasOne("Devify.Entity.Chapter", "Chapter")
                        .WithMany("Lessons")
                        .HasForeignKey("ChapterId");

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Devify.Entity.Notification", b =>
                {
                    b.HasOne("Devify.Entity.ApplicationUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Devify.Entity.Order", b =>
                {
                    b.HasOne("Devify.Entity.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserBuyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Devify.Entity.RefreshToken", b =>
                {
                    b.HasOne("Devify.Entity.ApplicationUser", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Devify.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Devify.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Devify.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Devify.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Devify.Entity.ApplicationUser", b =>
                {
                    b.Navigation("Creator");

                    b.Navigation("Notifications");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Devify.Entity.Category", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Devify.Entity.Chapter", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Devify.Entity.Course", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("CourseLanguages");

                    b.Navigation("DetailOrders");
                });

            modelBuilder.Entity("Devify.Entity.CourseLevel", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Devify.Entity.Creator", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Devify.Entity.Language", b =>
                {
                    b.Navigation("CourseLanguages");
                });

            modelBuilder.Entity("Devify.Entity.Lesson", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Devify.Entity.Order", b =>
                {
                    b.Navigation("DetailOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
